name: Lint package on pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: pnpm install --frozen-lockfile && pnpm lint
      - run: pnpm install --frozen-lockfile && pnpm lint
        working-directory: app
